services:
  - type: web
    name: yt-audio-downloader
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: YOUTUBE_API_KEY
        value: ${YOUTUBE_API_KEY}
      - key: ASSEMBLYAI_API_KEY
        value: ${ASSEMBLYAI_API_KEY}
