services:
  - type: web
    name: yt-audio-downloader
    env: docker            # ← must be “docker”
    dockerfilePath: ./Dockerfile
    # NO buildCommand or startCommand here—Dockerfile covers both.
    envVars:
      - key: YOUTUBE_API_KEY
        value: ${YOUTUBE_API_KEY}
      - key: ASSEMBLYAI_API_KEY
        value: ${ASSEMBLYAI_API_KEY}
